name: Download kafka-connect-s3 jar and upload to GitHub

on:
  workflow_dispatch:
    inputs:
      connector_version:
        description: 'Version of the Kafka Connect S3 Sink Connector'
        required: true
        default: '10.5.9'

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download kafka-connect-s3 JAR
        run: |
          curl -o kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar \
          "https://packages.confluent.io/maven/io/confluent/kafka/connect/kafka-connect-s3/${{ github.event.inputs.connector_version }}/kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar"

      - name: Upload JAR to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar
          path: kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar