name: Download kafka-connect-s3 jar and upload to S3

on:
  workflow_dispatch:
    inputs:
      connector_version:
        description: 'Version of the Kafka Connect S3 Sink Connector'
        required: true
        default: '10.5.9'

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download kafka-connect-s3 JAR
        run: |
          curl -o kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar \
          "https://packages.confluent.io/maven/io/confluent/kafka/connect/kafka-connect-s3/${{ github.event.inputs.connector_version }}/kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Upload JAR to S3
        run: |
          aws s3 cp kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar \
          s3://kafka-connect-s3-uploads/kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar