name: Upload Kafka Connect S3 Sink Connector

on:
  push:
    branches:
      - test-workflow  # Replace with your specific branch name
  workflow_dispatch:
    inputs:
      connector_version:
        description: 'Version of the Kafka Connect S3 Sink Connector'
        required: true
        default: '10.5.17'

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download S3 Sink Connector
        run: |
          curl -o kafka-connect-s3-sink.zip "https://packages.confluent.io/maven/io/confluent/kafka/connect/kafka-connect-s3/${{ github.event.inputs.connector_version }}/kafka-connect-s3-${{ github.event.inputs.connector_version }}.zip"

      - name: Extract Specific JAR
        run: |
          unzip -j kafka-connect-s3-sink.zip "confluentinc-kafka-connect-s3-${{ github.event.inputs.connector_version }}/lib/kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar" -d extracted

      - name: Upload JAR to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: kafka-connect-s3-sink-jar
          path: extracted/kafka-connect-s3-${{ github.event.inputs.connector_version }}.jar  # Uploads only the specific JAR file
