name: Upload Kafka Connect S3 Sink Connector

on:
  push:
    branches:
      - test-workflow
  workflow_dispatch:
    inputs:
      connector_version:
        description: 'Version of the Kafka Connect S3 Sink Connector'
        required: true
        default: '10.5.9'

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Fetch Latest Version if Not Specified
        id: get-latest
        run: |
          if [ -z "${{ github.event.inputs.connector_version }}" ]; then
            LATEST_VERSION=$(curl -s "https://packages.confluent.io/maven/io/confluent/kafka-connect-s3/maven-metadata.xml" | grep -oPm1 "(?<=<latest>)[^<]+")
            echo "Latest version is $LATEST_VERSION"
            echo "::set-output name=version::$LATEST_VERSION"
          else
            echo "::set-output name=version::${{ github.event.inputs.connector_version }}"
          fi

      - name: Download S3 Sink Connector
        run: |
          curl -o kafka-connect-s3-${{ steps.get-latest.outputs.version }}.jar \
          "https://packages.confluent.io/maven/io/confluent/kafka/connect/kafka-connect-s3/${{ steps.get-latest.outputs.version }}/kafka-connect-s3-${{ steps.get-latest.outputs.version }}.jar"

      - name: Upload JAR to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: kafka-connect-s3-sink-jar
          path: kafka-connect-s3-${{ steps.get-latest.outputs.version }}.jar
