name: Upload Kafka Connect S3 Sink Connector

on:
  workflow_dispatch:
    inputs:
      connector_version:
        description: 'Version of the Kafka Connect S3 Sink Connector'
        required: true
        default: '10.5.17'

jobs:
  download-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Download S3 Sink Connector
        run: |
          wget -O kafka-connect-s3-sink.zip "https://packages.confluent.io/maven/io/confluent/kafka/connect/kafka-connect-s3/${{ github.event.inputs.connector_version }}/confluentinc-kafka-connect-s3-${{ github.event.inputs.connector_version }}.zip"
          unzip kafka-connect-s3-sink.zip -d kafka-connect-s3-sink
          - name: Upload Artifact to GitHub
          uses: actions/upload-artifact@v4
          with:
            name: hello-world-jar
            path: plugin/build/libs/hello-world-*.jar  # Uploads all JARs built in the plugin directory
